const swaggerAutogen = require('swagger-autogen')();

const outputFile = './src/swagger/swagger-output.json'; // Output file path
const endpointsFiles = [
  './src/routes/studentsRoutes.js', // Path to your route files
  './src/routes/agentRoutes.js',
//   './src/routes/otherRoutes.js',
];

const doc = {
  info: {
    title: 'My API Documentation',
    description: 'API documentation generated by Swagger',
  },
  host: 'localhost:3000',
  schemes: ['http'], // Change to 'https' if using HTTPS
  basePath: '/student', // Base path for all routes
  tags: [
    { name: 'Student', description: 'APIs related to students' },
    { name: 'Agent', description: 'APIs related to agents' },
    // { name: 'Other', description: 'Miscellaneous APIs' },
  ],
};

swaggerAutogen(outputFile, endpointsFiles, doc);
